### ISSUE TITLE
数据集什么时候开源

### ISSUE THREAD

**Issue by jiahao68** [jarvishou829/SUPS#1]
非常感谢你们的工作，请问你们的数据集什么时候开源？

**Comment by Gong2Kun** [comment]
> 

你好，请问链接在哪呀，A、B我也没找到bag包

**Comment by jarvishou829** [comment]
> > 
> 
> 你好，请问链接在哪呀，A、B我也没找到bag包

On this repo. The `data_access.txt` file contains the link.

**Comment by Gong2Kun** [comment]
非常感谢，我已经找到了，但是在跑LIOSAM时遇到，“Point cloud ring channel not available, please configure your point cloud data!”，您们的lidar数据没有这个ring是吗？需要我写一个转换的程序

**Comment by Gong2Kun** [comment]
> > > 
> > 
> > 
> > 你好，请问链接在哪呀，A、B我也没找到bag包
> 
> On this repo. The `data_access.txt` file contains the link.

camera 0 to body-frame (imu),相机到IMU的转换矩阵为什么是0，0，0呀，看您的论文中传感器布局的话，IMU是在后面的，请问这个转换矩阵有具体的值吗

**Comment by jarvishou829** [comment]
> 非常感谢，我已经找到了，但是在跑LIOSAM时遇到，“Point cloud ring channel not available, please configure your point cloud data!”，您们的lidar数据没有这个ring是吗？需要我写一个转换的程序

You're right. The code of LIOSAM needs a little modification.

**Comment by jarvishou829** [comment]
> > > > 
> > > 
> > > 
> > > 你好，请问链接在哪呀，A、B我也没找到bag包
> > 
> > 
> > On this repo. The `data_access.txt` file contains the link.
> 
> camera 0 to body-frame (imu),相机到IMU的转换矩阵为什么是0，0，0呀，看您的论文中传感器布局的话，IMU是在后面的，请问这个转换矩阵有具体的值吗

That's a change for ease of use. Because this dataset is a simulated one. I set the translation of the cam2IMU to 0 in the open-sourced data, that the initialization and extrinsic parameters optimization can be much easier. Your can also use other configuration when recording the data by your self.

**Comment by WenZheDing** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你好，请问链接在哪呀，A、B我也没找到bag包
> > > 
> > > 
> > > On this repo. The `data_access.txt` file contains the link.
> > 
> > 
> > camera 0 to body-frame (imu),相机到IMU的转换矩阵为什么是0，0，0呀，看您的论文中传感器布局的话，IMU是在后面的，请问这个转换矩阵有具体的值吗
> 
> That's a change for ease of use. Because this dataset is a simulated one. I set the translation of the cam2IMU to 0 in the open-sourced data, that the initialization and extrinsic parameters optimization can be much easier. Your can also use other configuration when recording the data by your self.

您好，在vins-F_stereo_interial.yaml中camera到imu的转换矩阵 
  data: [0.0, 0.0, 1.0, -0.0,
         -1.0, 0.0, 0.0, -0.0,
         -0.0, -1.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 1.0]
似乎和论文中imu和camera的坐标系方向定义（均为前x左y上z）对不太上，请问在发布的数据中这部分也做了一些修改吗
