### ISSUE TITLE
Questions about the senario of SUPS

### ISSUE THREAD

**Issue by LainWeigh** [jarvishou829/SUPS#11]
Hi,

This is a great piece of work, thank you for your contributions.

I have been informed that I cannot log into SVL's cloud to get the SUPS dataset since SVL is not maintained from July 2022. But I am very eager to get the **parking lot senario** of the SUPS to make the vehicle explore autonomously. Is it possible to open source this senario? Once I have the source files for this senario, can I put it into other autonomous driving simulators and modify it? Can you give some examples of other autonomous driving simulators?

I am new to automatic driving, so thank you very much for your answer!

**Comment by jarvishou829** [comment]
As mentioned in our paper, the senario has already been open-sourced in our link. The scene is included in `/SUPS/virtual_scene/SUPS_scene.zip`. As for loading the scene to other simulator, this scene is built based on Unity according to SVL tutorial. So you may need to find instructions on other simulator to load unity based scene. Other famous simulator includes CARLA, Catographer, etc.

**Comment by LainWeigh** [comment]
Thank you for your answer!

I am trying to open the decompressed scene file `SUPS_scene.zip` with `Unity`, but `Unity` prompts me that this is not a valid file, so it cannot be opened. Similarly, using Unity-based driving simulators, such as `AirSim`, cannot be opened, too. What is the solution?

**Comment by jarvishou829** [comment]
Please follow this instruction on [building the simulator](https://www.svlsimulator.com/docs/installation-guide/build-instructions/).

**Comment by jarvishou829** [comment]
> 

Please follow this instruction on [building the simulator](https://www.svlsimulator.com/docs/installation-guide/build-instructions/).

**Comment by jarvishou829** [comment]
> Thank you for your answer!
> 
> I am trying to open the decompressed scene file `SUPS_scene.zip` with `Unity`, but `Unity` prompts me that this is not a valid file, so it cannot be opened. Similarly, using Unity-based driving simulators, such as `AirSim`, cannot be opened, too. What is the solution?

Please follow this instruction on [building the simulator](https://www.svlsimulator.com/docs/installation-guide/build-instructions/).
