### ISSUE TITLE
鱼眼相机的内参和畸变系数有吗？我在config文件里并没有找到

### ISSUE THREAD

**Issue by jiahao68** [jarvishou829/SUPS#2]

**Comment by jarvishou829** [comment]
The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`

**Comment by fliegend** [comment]
> The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`

Hi, the distortion params in ORB_stereo_inertial.yaml are all 0.0, however the all 4 fisheye camera images are undistorted as can be seen in rviz.
Could you please update the yaml with correct distortion params? So that the bag files can be helpful, many thanks.

**Comment by jarvishou829** [comment]
> > The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`
> 
> Hi, the distortion params in ORB_stereo_inertial.yaml are all 0.0, however the all 4 fisheye camera images are undistorted as can be seen in rviz. Could you please update the yaml with correct distortion params? So that the bag files can be helpful, many thanks.

We ran ORB using the two main camera which are pinhole ones not fisheye, So the the distortion params in ORB_stereo_inertial.yaml are all 0.0.

**Comment by jiahao68** [comment]
> > > The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`
> > 
> > 
> > Hi, the distortion params in ORB_stereo_inertial.yaml are all 0.0, however the all 4 fisheye camera images are undistorted as can be seen in rviz. Could you please update the yaml with correct distortion params? So that the bag files can be helpful, many thanks.
> 
> We ran ORB using the two main camera which are pinhole ones not fisheye, So the the distortion params in ORB_stereo_inertial.yaml are all 0.0.

files in config/ don't have intrinsic and distortion params of fishieye. Can you provide us with those information?

**Comment by fliegend** [comment]
> > > The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`
> > 
> > 
> > Hi, the distortion params in ORB_stereo_inertial.yaml are all 0.0, however the all 4 fisheye camera images are undistorted as can be seen in rviz. Could you please update the yaml with correct distortion params? So that the bag files can be helpful, many thanks.
> 
> We ran ORB using the two main camera which are pinhole ones not fisheye, So the the distortion params in ORB_stereo_inertial.yaml are all 0.0.

你好，我看你语义分割用的bev image都是去畸变后拼接的，其实我们就是想知道这里用到的fisheye畸变参数。rosbag中的fisheye topic都是没有去畸变的，如果没有提供畸变参数我们是没法直接使用您提供的rosbag数据集的。所以方便提供一下吗？感谢！

**Comment by jarvishou829** [comment]
> > > > The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`
> > > 
> > > 
> > > Hi, the distortion params in ORB_stereo_inertial.yaml are all 0.0, however the all 4 fisheye camera images are undistorted as can be seen in rviz. Could you please update the yaml with correct distortion params? So that the bag files can be helpful, many thanks.
> > 
> > 
> > We ran ORB using the two main camera which are pinhole ones not fisheye, So the the distortion params in ORB_stereo_inertial.yaml are all 0.0.
> 
> 你好，我看你语义分割用的bev image都是去畸变后拼接的，其实我们就是想知道这里用到的fisheye畸变参数。rosbag中的fisheye topic都是没有去畸变的，如果没有提供畸变参数我们是没法直接使用您提供的rosbag数据集的。所以方便提供一下吗？感谢！

The LGSVL site has been offline, and no direct configs of sensors can be download temporarily. However, I manage to find the configs used for BEV image generation from four fisheye cameras. These configs has been uploaded to the link in folder `SUPS/bag_file/config/pitch_30_fov_60/`. Hope it helps.

**Comment by fliegend** [comment]
> > > > > The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`
> > > > 
> > > > 
> > > > Hi, the distortion params in ORB_stereo_inertial.yaml are all 0.0, however the all 4 fisheye camera images are undistorted as can be seen in rviz. Could you please update the yaml with correct distortion params? So that the bag files can be helpful, many thanks.
> > > 
> > > 
> > > We ran ORB using the two main camera which are pinhole ones not fisheye, So the the distortion params in ORB_stereo_inertial.yaml are all 0.0.
> > 
> > 
> > 你好，我看你语义分割用的bev image都是去畸变后拼接的，其实我们就是想知道这里用到的fisheye畸变参数。rosbag中的fisheye topic都是没有去畸变的，如果没有提供畸变参数我们是没法直接使用您提供的rosbag数据集的。所以方便提供一下吗？感谢！
> 
> The LGSVL site has been offline, and no direct configs of sensors can be download temporarily. However, I manage to find the configs used for BEV image generation from four fisheye cameras. These configs has been uploaded to the link in folder `SUPS/bag_file/config/pitch_30_fov_60/`. Hope it helps.

The distortion coefficients in your uploaded .yaml files are also all 0.0. The extrinsic parameters are helpful. Anyway great thanks for your help :) . I may try other approaches.

In case others may need the distortion parameters, I've roughly estimated one for all 4 fisheyes: dist_coeffs = [-0.657, 0.39, 0.0, 0.0, -0.0995]

**Comment by jarvishou829** [comment]
> > > > > > The pinhole camera configs can be found in config/ORB_stereo_inertial.yaml. And the difference between fisheye cameras and pihole ones is only the set of `fisheye`, `Distorted` and `Xi` according to [LGSVL doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera). The detailed information can be found in the json files in `config/`
> > > > > 
> > > > > 
> > > > > Hi, the distortion params in ORB_stereo_inertial.yaml are all 0.0, however the all 4 fisheye camera images are undistorted as can be seen in rviz. Could you please update the yaml with correct distortion params? So that the bag files can be helpful, many thanks.
> > > > 
> > > > 
> > > > We ran ORB using the two main camera which are pinhole ones not fisheye, So the the distortion params in ORB_stereo_inertial.yaml are all 0.0.
> > > 
> > > 
> > > 你好，我看你语义分割用的bev image都是去畸变后拼接的，其实我们就是想知道这里用到的fisheye畸变参数。rosbag中的fisheye topic都是没有去畸变的，如果没有提供畸变参数我们是没法直接使用您提供的rosbag数据集的。所以方便提供一下吗？感谢！
> > 
> > 
> > The LGSVL site has been offline, and no direct configs of sensors can be download temporarily. However, I manage to find the configs used for BEV image generation from four fisheye cameras. These configs has been uploaded to the link in folder `SUPS/bag_file/config/pitch_30_fov_60/`. Hope it helps.
> 
> The distortion coefficients in your uploaded .yaml files are also all 0.0. The extrinsic parameters are helpful. Anyway great thanks for your help :) . I may try other approaches.
> 
> In case others may need the distortion parameters, I've roughly estimated one for all 4 fisheyes: dist_coeffs = [-0.657, 0.39, 0.0, 0.0, -0.0995]

Great thanks for your help. As far as I know, the origin LGSVL simulation platform used unified camera model and only Xi has to be set in practice, which is the distance from the virtual optical center to the original optical center. And in my settings the distortion parameters are not especially set. And as can be seen in [their doc](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#color-camera) the distortion parameters is default to be an empty list.
