### ISSUE TITLE
请问轨迹真值文件在哪里下载?

### ISSUE THREAD

**Issue by kylelee2023** [jarvishou829/SUPS#3]

**Comment by jarvishou829** [comment]
We use the GPS topic as the ground truth trajectory in the simulation.

**Comment by kylelee2023** [comment]
感谢您的反馈，我们想利用真值轨迹来拼接激光点云构建真值地图，尝试使用GPS topic轨迹进行插值来拼接对应时刻的激光数据，发现点云地图很模糊，可否提供每一帧激光的gt pose呢？

**Comment by jarvishou829** [comment]
> 感谢您的反馈，我们想利用真值轨迹来拼接激光点云构建真值地图，尝试使用GPS topic轨迹进行插值来拼接对应时刻的激光数据，发现点云地图很模糊，可否提供每一帧激光的gt pose呢？

Sorry for this problem, but the bag file is the raw data that all we can get from the simulation platform. Our original intention dose not take the pointcloud splicing into account. This problem may comes from the time-lag.
