### ISSUE TITLE
请问使用IPM产生BEV图像的代码方便参考一下吗？

### ISSUE THREAD

**Issue by Gong2Kun** [jarvishou829/SUPS#4]
请问使用IPM产生BEV图像的代码方便参考一下吗？

**Comment by jarvishou829** [comment]
This part is not prepared for open-source, because it's part of the work of our teammates. Lots of other works realize analogous functions. The keywords may be inverse perspective transformation. However, feel free to contact me by email if you do need a rough version of code which is not clean.

**Comment by Gong2Kun** [comment]
Thank you very much！This is my email：gongkun@mail.nwpu.edu.cn

**Comment by Gong2Kun** [comment]
![uTools_1685372113123](https://github.com/jarvishou829/SUPS/assets/85012104/19a43175-0e3b-46a1-b6e2-e51d23d82f00)
请问这个深度值是不是存在问题啊，这是我把车道线的深度图的点云可视化之后，是歪着的，您确定这个深度相机和main的像素是一一对应的吗
                float im_Z=img_depth.at<uchar>(i,j);
                point.x=0.001*im_Z*(i-cx)/fx;   
                point.y=0.001*im_Z*(j-cy)/fx;
                point.z=0.001*im_Z;
这是转成点云的代码

**Comment by Gong2Kun** [comment]
> 

这是用pcl可视化的点云，不是图像

**Comment by Gong2Kun** [comment]
> ![uTools_1685372113123](https://user-images.githubusercontent.com/85012104/241758620-19a43175-0e3b-46a1-b6e2-e51d23d82f00.png) 请问这个深度值是不是存在问题啊，这是我把车道线的深度图的点云可视化之后，是歪着的，您确定这个深度相机和main的像素是一一对应的吗 float im_Z=img_depth.at(i,j); point.x=0.001_im_Z_(i-cx)/fx; point.y=0.001_im_Z_(j-cy)/fx; point.z=0.001*im_Z; 这是转成点云的代码

后面我把深度图转换成了点云图好像也不太对

**Comment by jarvishou829** [comment]
> > ![uTools_1685372113123](https://user-images.githubusercontent.com/85012104/241758620-19a43175-0e3b-46a1-b6e2-e51d23d82f00.png) 请问这个深度值是不是存在问题啊，这是我把车道线的深度图的点云可视化之后，是歪着的，您确定这个深度相机和main的像素是一一对应的吗 float im_Z=img_depth.at(i,j); point.x=0.001_im_Z_(i-cx)/fx; point.y=0.001_im_Z_(j-cy)/fx; point.z=0.001*im_Z; 这是转成点云的代码
> 
> 后面我把深度图转换成了点云图好像也不太对

Sorry for this mistake. I double check that in this open-sourced version of data the depth camera is bound with the front camera (one of the surround cameras) not main camera (one of the stereo cameras). The transmission and other configs can be seen in `config/*.json` files.

**Comment by Gong2Kun** [comment]
> > > ![uTools_1685372113123](https://user-images.githubusercontent.com/85012104/241758620-19a43175-0e3b-46a1-b6e2-e51d23d82f00.png) 请问这个深度值是不是存在问题啊，这是我把车道线的深度图的点云可视化之后，是歪着的，您确定这个深度相机和main的像素是一一对应的吗 float im_Z=img_depth.at(i,j); point.x=0.001_im_Z_(i-cx)/fx; point.y=0.001_im_Z_(j-cy)/fx; point.z=0.001*im_Z; 这是转成点云的代码
> > 
> > 
> > 后面我把深度图转换成了点云图好像也不太对
> 
> Sorry for this mistake. I double check that in this open-sourced version of data the depth camera is bound with the front camera (one of the surround cameras) not main camera (one of the stereo cameras). The transmission and other configs can be seen in `config/*.json` files.

那也不对啊，depth的频率是20HZ，但是front相机的频率只有7Hz

**Comment by Gong2Kun** [comment]
我感觉是你们想做main的深度，但是给添加错位置了导致深度相机位置和main的不一致

**Comment by jarvishou829** [comment]
> > > > ![uTools_1685372113123](https://user-images.githubusercontent.com/85012104/241758620-19a43175-0e3b-46a1-b6e2-e51d23d82f00.png) 请问这个深度值是不是存在问题啊，这是我把车道线的深度图的点云可视化之后，是歪着的，您确定这个深度相机和main的像素是一一对应的吗 float im_Z=img_depth.at(i,j); point.x=0.001_im_Z_(i-cx)/fx; point.y=0.001_im_Z_(j-cy)/fx; point.z=0.001*im_Z; 这是转成点云的代码
> > > 
> > > 
> > > 后面我把深度图转换成了点云图好像也不太对
> > 
> > 
> > Sorry for this mistake. I double check that in this open-sourced version of data the depth camera is bound with the front camera (one of the surround cameras) not main camera (one of the stereo cameras). The transmission and other configs can be seen in `config/*.json` files.
> 
> 那也不对啊，depth的频率是20HZ，但是front相机的频率只有7Hz

I check the json file and the frequency of front camera is 20Hz. You mean the frequency of depth camera is 7 Hz?

**Comment by jarvishou829** [comment]
> 我感觉是你们想做main的深度，但是给添加错位置了导致深度相机位置和main的不一致

We naturally want to provide the depth information. And as you mentioned, the depth information was not perfactly bound with other cameras. However, the LGSVL platform provides no more survice, we will work on build and release a new version of data if possible.

**Comment by Gong2Kun** [comment]
> > > > > ![uTools_1685372113123](https://user-images.githubusercontent.com/85012104/241758620-19a43175-0e3b-46a1-b6e2-e51d23d82f00.png) 请问这个深度值是不是存在问题啊，这是我把车道线的深度图的点云可视化之后，是歪着的，您确定这个深度相机和main的像素是一一对应的吗 float im_Z=img_depth.at(i,j); point.x=0.001_im_Z_(i-cx)/fx; point.y=0.001_im_Z_(j-cy)/fx; point.z=0.001*im_Z; 这是转成点云的代码
> > > > 
> > > > 
> > > > 后面我把深度图转换成了点云图好像也不太对
> > > 
> > > 
> > > Sorry for this mistake. I double check that in this open-sourced version of data the depth camera is bound with the front camera (one of the surround cameras) not main camera (one of the stereo cameras). The transmission and other configs can be seen in `config/*.json` files.
> > 
> > 
> > 那也不对啊，depth的频率是20HZ，但是front相机的频率只有7Hz
> 
> I check the json file and the frequency of front camera is 20Hz. You mean the frequency of depth camera is 7 Hz?

![图片](https://github.com/jarvishou829/SUPS/assets/85012104/857b757e-3ac2-4e4c-aa54-a4b89d299a34)
或许直接看bag文件会直观一点是7Hz

**Comment by Gong2Kun** [comment]
双目的深度话题是有问题的，这个方便修改一下吗？我这边已经做了挺多工作了，比较需要这个深度图？

**Comment by notabigfish** [comment]
> This part is not prepared for open-source, because it's part of the work of our teammates. Lots of other works realize analogous functions. The keywords may be inverse perspective transformation. However, feel free to contact me by email if you do need a rough version of code which is not clean.

Hi, could you please send me this rough version of code? My email address is zsgoal@163.com. Thanks!
