### ISSUE TITLE
encounter error use rosbag

### ISSUE THREAD

**Issue by WenZheDing** [jarvishou829/SUPS#5]
i play the bag in baidunetdisk,but i failed to visualize both pointcloud and image in rviz,
for pointcloud: For frame []: Fixed Frame [map] does not exist
for image : According to the loaded plugin descriptions the class image_transport/main_sub with base class type image_transport::SubscriberPlugin does not exist. Declared types are image_transport/compressedDepth_sub image_transport/compressed_sub image_transport/raw_sub image_transport/theora_sub

**Comment by WenZheDing** [comment]
跑代码的时候会报错[ERROR] [1684756067.583477740]: Point cloud ring channel not available, please configure your point cloud data! 想知道在LIOSAM里是怎么处理的

**Comment by jarvishou829** [comment]
> 非常感谢，我已经找到了，但是在跑LIOSAM时遇到，“Point cloud ring channel not available, please configure your point cloud data!”，您们的lidar数据没有这个ring是吗？需要我写一个转换的程序

You're right. The code of LIOSAM needs a little modification.

_Originally posted by @jarvishou829 in https://github.com/jarvishou829/SUPS/issues/1#issuecomment-1517100905_

**Comment by WenZheDing** [comment]
感谢 想问下第一个问题（rviz可视化的问题）您有遇到吗

**Comment by WenZheDing** [comment]
顺便想问下 计算ring的代码可否分享一下呢，或是提供下雷达在垂直方向的视场角范围和分辨率

**Comment by Gong2Kun** [comment]
想问一下深度图像“camera/depth"和RGB图像“/camera/main"是对应的吗？换句话说就是RGB相机对应的深度图是“camera/depth"吗？两者的对应像素之间是相互对应的吗，就像现实中的深度相机一样

**Comment by jarvishou829** [comment]
> 感谢 想问下第一个问题（rviz可视化的问题）您有遇到吗

I have not used rviz to directly visualize the bag information. From my view, the image topic visualization problem is due to the type of the ros topic. The topic type of the image is sensor_msgs/CompressedImage rather than not compressed one. The pointcloud visualization problem is due to the frame ID problem. The simulation platform publish empty frame ID topic. If you want to directly visulize them using rviz, Both of these problems may be solved by writing a ROS listener and publisher to sovle the mentioned problems and republish the topics.

**Comment by jarvishou829** [comment]
> 顺便想问下 计算ring的代码可否分享一下呢，或是提供下雷达在垂直方向的视场角范围和分辨率

Sorry that the modified LIO_SAM code was not saved. We solved this refering to the issues in LIO_SAM and blogs. The detailed LiDAR configuration can be flound in `SUPS/bag_file/config/*.json`.

**Comment by jarvishou829** [comment]
> 想问一下深度图像“camera/depth"和RGB图像“/camera/main"是对应的吗？换句话说就是RGB相机对应的深度图是“camera/depth"吗？两者的对应像素之间是相互对应的吗，就像现实中的深度相机一样

Yes it is. The depth image is bound with the main camera. This was realized due to the use of the siulation sensors. We ignore the collision volume and simply use the same extrinsic and intrinsic parameters on the depth and main camera.

**Comment by WenZheDing** [comment]
> > 感谢 想问下第一个问题（rviz可视化的问题）您有遇到吗
> 
> I have not used rviz to directly visualize the bag information. From my view, the image topic visualization problem is due to the type of the ros topic. The topic type of the image is sensor_msgs/CompressedImage rather than not compressed one. The pointcloud visualization problem is due to the frame ID problem. The simulation platform publish empty frame ID topic. If you want to directly visulize them using rviz, Both of these problems may be solved by writing a ROS listener and publisher to sovle the mentioned problems and republish the topics.

thanks for your reply. this solved my problem.
