### ISSUE TITLE
What is the RGB value of four corners of one parking slot?

### ISSUE THREAD

**Issue by notabigfish** [jarvishou829/SUPS#9]
Hi,

thanks for building this awesome dataset. I want to use this data to do parking slot detection. Could you please tell me the RGB of four corners of one parking slot? Thanks

**Comment by jarvishou829** [comment]
The RGB value of corners can be get by a simple python script, or a screen color picker like in [runoob](https://c.runoob.com/front-end/6214/#7b2246)

**Comment by notabigfish** [comment]
> 

Thanks! I'll try this method.
